name: mdbook -> gh pages

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-linkcheck: true
          use-toc: true
          use-opengh: true
      - run: cd gh-pages && mdbook build && cp -f ./src/images/favicon.jpeg ./book/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages/book
